import type { Space } from '@/types'

export const MOCK_SPACES: Space[] = [
  {
    id: '1',
    title: 'Ботаника',
    description: 'Светлый кабинет с панорамным окном. Идеально подходит для мастеров маникюра, бровистов и технологов.',
    address: 'ул. Примерная 12',
    pricePerHour: 1300,
    pricePerDay: 7000,
    area: 2,
    capacity: 2,
    images: [],
    type: 'office',
    tags: ['Маникюр', 'Бровист'],
    rating: 4.8,
  },
  {
    id: '2',
    title: 'Лаванда',
    description: 'Уютное пространство с хорошим освещением.',
    address: 'ул. Примерная 14',
    pricePerHour: 1500,
    pricePerDay: 8000,
    area: 3,
    capacity: 3,
    images: [],
    type: 'office',
    tags: ['Маникюр'],
    rating: 4.9,
  },
  {
    id: '3',
    title: 'Минт',
    description: 'Просторный кабинет для нескольких мастеров.',
    address: 'ул. Примерная 16',
    pricePerHour: 1200,
    pricePerDay: 6500,
    area: 4,
    capacity: 4,
    images: [],
    type: 'coworking',
    tags: ['Переговорки'],
    rating: 4.7,
  },
  {
    id: '4',
    title: 'Розовый',
    description: 'Стильный кабинет в розовых тонах.',
    address: 'ул. Примерная 18',
    pricePerHour: 1400,
    pricePerDay: 7500,
    area: 2,
    capacity: 2,
    images: [],
    type: 'office',
    tags: ['Бровист'],
    rating: 4.6,
  },
]
